### ISSUE TITLE
doubt on multi cam - imu  calibration

### ISSUE THREAD

**Issue by arjunskumar** [shockwaveHe/MCVIO#1]
could you share details on how you did the calibration between 2 cameras and IMU?

**Comment by shockwaveHe** [comment]
Our algorithm does not support calibration between cameras and IMU. The extrinsics are calibrated by other algorithms. One typical approach I used is using VINS-Mono to calibrate IMU and monocular camera one by one (They provide a good calibration module). Since we use the same coordinate system as VINS-Mono, the output can be directly applied to our algorithm. I think that will help.

**Comment by shockwaveHe** [comment]
Maybe later I will add the calibration module into it.

**Comment by shockwaveHe** [comment]
@arjunskumar For calibration, resently we are using kalibr. https://github.com/ethz-asl/kalibr/wiki. This one is better.

**Comment by arjunskumar** [comment]
@shockwaveHe Thanks
