### ISSUE TITLE
example launch file to run euroc dataset

### ISSUE THREAD

**Issue by ryanESX** [shockwaveHe/MCVIO#3]
Hi, you mentioned this code has been test on euroc dataset. Is it possible to provide the launch file to run it?

**Comment by shockwaveHe** [comment]
I add a configuration file for EuRoC dataset which use both of the cameras. The configuration file is under `MCVO/config/MCVIO/EuRoC/`. Before using it remember to change the path parameters in it.

In this config file I assume that you have preprocessed the EuRoC bag files so that the two cameras have different frame_id (the frame_id will be both 'cam0' when directly download from the EuRoC website but our algorithm requires different frame_id). 

To launch it 
`roslaunch mcvio MCVIO_euroc.launch`

Note that I deleted euroc related configuration and files before, so I am not able to test this new configuration. Don't hesitate to tell me if you have some problems.

**Comment by ryanESX** [comment]
Thanks, it is working. But I have to modified both cam0 and cam1 frame_id to make it work.  What I've done is to make `sensor_list: ['cam_0','cam_1']` name same same as `frame_id`. Is this limitation mandatory?

**Comment by shockwaveHe** [comment]
Yes. We use `frame_id` as indicator for different camera input, so you should make sure that the inputs have diffrenent `frame_id` and configure them correctly in the configuration file.

**Comment by DuyTPresent** [comment]
> Thanks, it is working. But I have to modified both cam0 and cam1 frame_id to make it work. What I've done is to make `sensor_list: ['cam_0','cam_1']` name same same as `frame_id`. Is this limitation mandatory?

Could you share the config file for Euroc dataset?
